[package]
name = "shader-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["debug"] }
leafwing-input-manager = "*"
strum = { version = "*", features = ["derive"] }
indexmap = "*"
nonmax = "*"
rand = "*"
xs-bevy-state-scoped-systems = { git = "https://github.com/XSWare/xs-bevy-state-scoped-systems" }

[build-dependencies]
copy_to_output = "*"
